version: '3.8'

services:
  dify-sync:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dify-sync-manager
    restart: unless-stopped
    
    # 端口映射
    ports:
      - "5000:5000"
    
    # 环境变量（从 .env 文件加载）
    env_file:
      - .env
    
    # 数据持久化
    volumes:
      - ./data:/app/data
      - ./sync.log:/app/sync.log
      - ./sync_database.db:/app/sync_database.db
    
    # 健康检查
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    
    # 日志配置
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # 网络配置
    networks:
      - dify-sync-network

networks:
  dify-sync-network:
    driver: bridge